title: S³C
big_title: Sustainable, Secure, and Smart Collaboration Workshop
email: mapellegrino@unisa.it
date: 20<sup>th</sup> September, 2023
date1: 23<sup>th</sup> June 2023
date2: 14<sup>th</sup> July 2023
date3: 21<sup>th</sup> July 2023
date4: 31<sup>th</sup> July 2023
address: University of Turin, Turin, Italy
description: >-
    The Sustainable, Secure, and Smart Collaboration (S³C) workshop is meant to connect researchers, 
    industries, educators, and technologists involved in different and diverse areas connected to HCI 
    blended with immersive systems, smart cities, and security awareness which can take advantage of 
    the collaboration.
about_s3c: >-
    We live in a world where no individual is independent of those around them. Hence, interconnection, 
    interdependence and collaboration are shaping the framework of modern society as they stimulate the
    transition to a more sustainable society. It is how we collaborate today that will strengthen our 
    relationships in the future. By promoting a collaborative environment, you are driving and enabling
    sustainable practices allowing merging different perspectives to help guide decisions, increasing 
    trust, promoting an innovative culture and driving innovation. 
    <br />
    Collaboration is generally based on interactions between people. However, technology is rapidly 
    shaping our lives, requiring us to redefine collaborative environments, letting geographically 
    distant people to easily communicate and work together, experiencing immersive virtual reality 
    which emulates real social interactions, and designing interactive and smart environments. Hence, 
    this workshop focuses on sustainable and smart collaboration, which might also take place in 
    virtual, remote and online settings.
    <br />
    While it represents a step forward in breaking down geographical and social barriers, 
    virtual environments should carefully deal with security aspects, above all when young and 
    inexperienced users are involved. Hence, besides focusing on sustainable and smart collaboration, 
    we should not forgive the security concerns.

baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jekyllrb
github_username: jekyll

# Build settings
theme: minima
plugins:
    - jekyll-feed
